### ISSUE TITLE
Allow whitespace in comment characters

### ISSUE THREAD

**Issue by sheaf** [PanAeon/vscode-tmgrammar-test#9]
I've been using this library to test the [Haskell VS code syntax highlighting extension](https://github.com/JustusAdam/language-haskell) and it's been extremely useful, thanks!    

One issue I have is that, when I am trying to address issues in the syntax highlighting involving comments, sometimes the extra test lines interfere with the syntax highlighting in VS Code, so that the rendered highlighting is different from what `vscode-tmgrammar-test` computes. That's fine, that's to be expected, as those lines are stripped from the input.

However it would help if `vscode-tmgrammar-test` allowed spaces in the comment string that it uses to recognise tests. Specifically, I would like to be able to use:

```
  -- SYNTAX TEST "source.haskell" "Indented data declarations"
```

(note the two spaces before `--`). Then `vscode-tmgrammar-test` would process the lines starting with 2 blank spaces and then `--`. At the moment if I try this I get the error:

```
Error: Expecting the first line in the syntax test file to be in the following format:
<comment character(s)> SYNTAX TEST "<language identifier>"  ("description")?

    at parseHeader [...]
```

**Comment by PanAeon** [comment]
Hi @sheaf , it is totally possible. I'm not sure if white space before comment character won't cause any confusion, as it's really easy to miss out. Maybe ```'  --' SYNTAX TEST ``` or smth...
BTW, as for the syntax itself, the runner first removes all lines with syntax assertions, and only then runs syntax highlighting on them. 
So I think it's more a convenience issue, because extra comments might break the syntax highlighting of the test case in the editor, but if the same code is extracted into a separate file, you can get scopes via vscode inspector, then put them in the assertions, and the test case should behave as the code itself, even the lines with indentations. At least in theory))

**Comment by PanAeon** [comment]
@sheaf, I think we can put a flag into the header, something like
```-- SYNTAX TEST "source.haskell" "Indented data declarations" +AllowMiddleLineAssertions```
with this enabled, each line that starts with `<space>*``<comment_characters>` will be processed as an assertion. The downside is that you won't be able to test single line comments with this approach, but I think you'll still be able to set `<comment characters>` as '---' and it won't interfere with the regular comments

**Comment by sheaf** [comment]
Cool, that sounds good to me.    

BTW is there a way to have wildcards in scopes, like ` keyword.*` which would match on any scope starting with `keyword`? I think that could be useful.

Thanks again for the library.

**Comment by PanAeon** [comment]
@sheaf I have pushed a new realease with `+AllowMiddleLineAssertions` flag to npm. I'll create a new ticket for `keyword.*`

**Comment by sheaf** [comment]
Excellent, thank you.
